version: '3.1'
services:
  webserver:
    image: 'nginx:alpine'
    working_dir: /app
    volumes:
      - '.:/app'
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8000:80'
    depends_on:
      - php-fpm
  php-fpm:
    build: ./php-fpm
    working_dir: /app
    environment:
      OTEL_PHP_AUTOLOAD_ENABLED: "true"
      OTEL_TRACES_EXPORTER: "console"
      OTEL_METRICS_EXPORTER: "none"
      OTEL_LOGS_EXPORTER: "console"
    volumes:
      - '.:/app'
      - './php-fpm/php-ini.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
